Add refresh token expiry hook
catalyst/django-oidc-provider pull request #15
Opened 2020-01-29 00:44 UTC by zacps

This adds a hook which is used to determine whether an access token is still valid, or should be expired.

2020-01-29 03:34 UTC, zacps commented on docs/sections/settings.rst
> +.. autofunction:: default_refresh_token_alive_hook
I'm not sure I'm happy with how this documentation renders. It does have the advantage of not having to duplicate the docs between `settings.py` and `settings.rst`.

2020-01-29 21:54 UTC, zacps commented
The `cleartokens` command is the approach taken by [Django OAuth Toolkit](https://django-oauth-toolkit.readthedocs.io/en/latest/management_commands.html#cleartokens).

2020-02-03 20:36 UTC, adamlynam-catalyst commented
Not part of your changes, but I noticed that `TokenEndpoint.validate_params()` method is very long. I am sure it all works correctly, but that is a lot of code to grok at once.

2020-02-03 22:53 UTC, adamlynam-catalyst requested changes
> In the event a refresh token is expired it is immediately removed from the database, along with the access token.

> Deleting tokens when they are no longer valid is different to django's session management. It might be more idiomatic to keep 'dead' tokens in the database and add a CLI command `cleartokens` to remove them.

I agree that being consistent in approach is worthwhile. However, for now, deleting the tokens is fine; we can revisit it another time to bring it in line with the Django paradigm of deleting through an offline operation later.

> This approach, while flexible, leaves a lot to the consumer of the provider. It may be more useful to provide fixed options for how refresh tokens should expire.

The implication from the spec seems to be that refresh tokens work indefinitely, unless revoked. I think this hook provides flexibility to expire them another way and anticipating that would probably leave us falling short.

>     * Subsequent requests to routes behind `protected_resource_view` will return HTTP 401 unauthorised and send the `WWW-Authenticate` header.
>       See [6750#3](https://tools.ietf.org/html/rfc6750#section-3)

Is it okay that if the refresh token is expired that the connected access token stops working too? I understand the two are conflated in the provider implementation and it seems like in all practical implementations this is desirable. I can only think of a very hypothetical situation where refresh tokens are immediately expired and the original access token issued together with it immediately stops working too. Perhaps that would be unexpected or unwanted behaviour?

^ This last one might do with an in person chat, I may just be totally misunderstanding the expectation here.

Above just discussion, only actual change required is the test description.

2020-02-03 22:53 UTC, adamlynam-catalyst commented on oidc_provider/tests/cases/test_token_endpoint.py
> +        """
If I am following correctly, I think this test has the wrong comment.

2020-02-03 23:28 UTC, zacps commented
Authorisation providers are [allowed to chose](https://tools.ietf.org/html/rfc6749#section-1.5) when to issue a refresh token. I think that'd handle the case when you don't want a valid refresh token to exist but want a access token.

Currently the provider unconditionally issues refresh tokens, adding a hook to determine whether to issue one is something I've considered.

2020-02-04 00:55 UTC, adamlynam-catalyst commented
> Authorisation providers are [allowed to chose](https://tools.ietf.org/html/rfc6749#section-1.5) when to issue a refresh token. I think that'd handle the case when you don't want a valid refresh token to exist but want a access token.
> 
> Currently the provider unconditionally issues refresh tokens, adding a hook to determine whether to issue one is something I've considered.

I agree, that sounds a much better way of handling the situation. Perhaps something we can add to the backlog, doesn't feel like it should be in the scope of this change.

2020-02-04 03:00 UTC, adamlynam-catalyst approved these changes
LGTM

2020-02-04 03:04 UTC, merged